### ISSUE TITLE
Abbreviations of Mâlatîmâdhava  in AP90

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#319]
A user submitted a correction as follows, for AP90:
```
Case 23551: 10/18/2016 dict=AP90, L= 4762, hw=avalaMb, user=geymonat
old = under meaning number 5 after vaiklavyam the mAlatImAdhava il abbreviated as Ma4l.
new = Mâl. (like it is always abbreviated)

```
In this one case, the text shows an acute accent over the 'a' in Mal'  (that's what the a4 means):
![image](https://cloud.githubusercontent.com/assets/6393033/20043699/0d5fb66e-a45f-11e6-9fbc-d5541a805ec1.png)

The spelling of this work (in HK) is as shown by the user.

A search of ap90.txt shows that there are 197 such instances of 'Ma4l.'

Also, there are 864 cases in ap90.txt abbreviated as 'Ma10l.'  (the a10 means a with circumflex, which
is the usual way ap90 prints a long-a, for instance 'Bha10sha' is coding used on 1st line of the image above. ).

I'm inclined to change all the 'Ma4l.' to 'Ma10l.' in ap90.

What do others think?

**Comment by gasyoun** [comment]
> What do others think?

As usual, same work lives under 2-4 abbreviations. If he's sure that's the same work, should unite.

**Comment by Andhrabharati** [comment]
I guess, all this is done in recent work on AP90 by @funderburkjim and this issue could now be closed.

**Comment by drdhaval2785** [comment]
वैक्लव्यं Māl. 8 

We see this in the frontend. It seems to have been corrected.

**Comment by gasyoun** [comment]
> We see this in the frontend

Guess we should still not this graphical correspondence anywhere Mál. = Māl.
